services:
  web:
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
    working_dir: /var/www/html
    entrypoint: ["sh", "-c", "chmod -R 775 /var/www/html && php-fpm"]

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel_ucrm
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_USER: laravel_ucrm
      MYSQL_PASSWORD: password123
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: ["sh", "-c", "chmod -R 775 /var/www/html && tail -f /dev/null"]

  node:
    image: node:18
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"

volumes:
  dbdata:
